import './globals.css'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'APP NAME',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-montserrat">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
